### ISSUE TITLE
The SUtil.hx Problem

### ISSUE THREAD

**Issue by StefanBETA2008** [MAJigsaw77/FNF-Android-Porting#12]
I Got This Error:
![Screenshot_20220910-151205~2](https://user-images.githubusercontent.com/109828559/189494231-9c8d137c-a985-4dbb-b4fc-096c1a51ff99.png)

How To Fix This MAJigsaw77

**Comment by MAJigsaw77** [comment]
-_- use the latest one from here

**Comment by StefanBETA2008** [comment]
Nevermind, I Fixed 😑. Im Stupid, But Thanks 🙂
