### ISSUE TITLE
Android

### ISSUE THREAD

**Issue by Konraiser** [MAJigsaw77/FNF-Android-Porting#13]
If possible make fullscreen on android?

**Comment by StefanBETA2008** [comment]
> If possible make fullscreen on android?

If You Don't Added The Lime 7.9.0 And Openfl 9.1.0 On The main.yml, You Can Get Full Screen, But The Icon It's Just Haxelib Logo

**Comment by MaysLastPlayGithub** [comment]
> > If possible make fullscreen on android?
> 
> If You Don't Added The Lime 7.9.0 And Openfl 9.1.0 On The main.yml, You Can Get Full Screen, But The Icon It's Just Haxelib Logo

Nah You Need Add On Main.yml Lime (for icon) and Openfl 9.1.0 for full screen if you using Sirox's metod (idk Guys On Saw's Server Say It's Sirox's Metod sooo)

**Comment by VegethYT** [comment]
> If possible make fullscreen on android?

Bro just go in main.yml and put haxelib install lime 7.9.0 and haxelib install openfl 9.1.0 then go to setup lime and add haxelib set lime 7.9.0 and haxelib set openfl 9.1.0

**Comment by MAJigsaw77** [comment]
This is the fix
