### ISSUE TITLE
The MusicBeatState And MusicBeatSubState Problem

### ISSUE THREAD

**Issue by StefanBETA2008** [MAJigsaw77/FNF-Android-Porting#15]
I Have This Code Error When I Just Ported Something:
`source/MusicBeatSubstate.hx:73: characters 4-27 : Controls has no field removeFlxInput
source/MusicBeatState.hx:60: characters 4-27 : Controls has no field removeFlxInput
source/MusicBeatState.hx:118: characters 4-27 : Controls has no field removeFlxInput
source/MusicBeatState.hx:121: characters 4-27 : Controls has no field removeFlxInput
source/MusicBeatSubstate.hx:51: characters 4-27 : Controls has no field removeFlxInput
source/MusicBeatState.hx:96: characters 4-27 : Controls has no field removeFlxInput`
Help Me Guys Please

**Comment by StefanBETA2008** [comment]
Nevermind, I Fixed

**Comment by StefanBETA2008** [comment]
Again, I Can't Fix This:
`source/MusicBeatSubstate.hx:73: characters 4-27 : Controls has no field removeFlxInput
source/MusicBeatState.hx:60: characters 4-27 : Controls has no field removeFlxInput
source/MusicBeatState.hx:118: characters 4-27 : Controls has no field removeFlxInput
source/MusicBeatState.hx:121: characters 4-27 : Controls has no field removeFlxInput
source/MusicBeatSubstate.hx:51: characters 4-27 : Controls has no field removeFlxInput
source/MusicBeatState.hx:96: characters 4-27 : Controls has no field removeFlxInput`

**Comment by MAJigsaw77** [comment]
There's no remove FlxInput, now is ControlsInput

**Comment by StefanBETA2008** [comment]
> There's no remove FlxInput, now is ControlsInput

Nevermind, I Fixed The Problem Again
