### ISSUE TITLE
The Another New SUtil Problem Issue

### ISSUE THREAD

**Issue by StefanBETA2008** [MAJigsaw77/FNF-Android-Porting#19]
`source/SUtil.hx:184: characters 13-18 : Class<android.Hardware> has no field toast
source/SUtil.hx:184: characters 47-68 : Type not found : ToastType
source/SUtil.hx:189: characters 12-17 : Class<android.Hardware> has no field toast
source/SUtil.hx:189: characters 68-89 : Type not found : ToastType
source/SUtil.hx:163: characters 13-18 : Class<android.Hardware> has no field toast
source/SUtil.hx:163: characters 75-96 : Type not found : ToastType
source/SUtil.hx:202: characters 12-17 : Class<android.Hardware> has no field toast
source/SUtil.hx:202: characters 68-89 : Type not found : ToastType`
How To Fix This Than?

**Comment by StefanBETA2008** [comment]
Nevermind. It's Fixed.

**Comment by Popuck** [comment]
how?
