### ISSUE TITLE
The Android Hardware Issue 2

### ISSUE THREAD

**Issue by StefanBETA2008** [MAJigsaw77/FNF-Android-Porting#23]
`source/FunkinLua.hx:54: characters 8-24 : Type not found : android.Hardware
source/GameOverSubstate.hx:13: characters 8-24 : Type not found : android.Hardware
source/GameOverSubstate.hx:70: characters 4-12 : Type not found : Hardware
source/FunkinLua.hx:2180: characters 4-12 : Type not found : Hardware
source/options/GameplaySettingsSubState.hx:28: characters 8-24 : Type not found : android.Hardware
source/options/GameplaySettingsSubState.hx:229: characters 4-12 : Type not found : Hardware`

How To Fix This @MAJigsaw77 ?

**Comment by Randomxdp** [comment]
Hardware is now Tools

**Comment by StefanBETA2008** [comment]
> Hardware is now Tools

Really? Damn, I Didn't Know

**Comment by StefanBETA2008** [comment]
Yeah, This It's Worked 🙂. Thanks

**Comment by Popuck** [comment]
bruh💀
