### ISSUE TITLE
pls help

### ISSUE THREAD

**Issue by Robert124l** [MAJigsaw77/FNF-Android-Porting#28]
i try to port my mod with phsych engine 6.2 but visual studio or android studio just don't want to read the code.
![Captura de pantalla (158)](https://user-images.githubusercontent.com/102814421/206830235-29773a8b-27e9-4806-a836-0cc9bb03396b.png)

**Comment by MAJigsaw77** [comment]
You don't have the flixel stuff in the `mobile` folder `Vpad, Hitbox, Joystick, Button`

**Comment by StefanBETA2008** [comment]
Yeah, Add The ``FlxJoystick.hx``, ``FlxHitbox.hx``, ``FlxButton`` And ``FlxVpad.hx``

**Comment by MAJigsaw77** [comment]
It's FlxVirtualPad

**Comment by StefanBETA2008** [comment]
> It's FlxVirtualPad

Oh, Sorry. I Didn't Read It
