### ISSUE TITLE
Build fails with "You cannot access the flash package while in a macro (for flash.display.BitmapData)"

### ISSUE THREAD

**Issue by Endergreen12** [MAJigsaw77/FNF-Android-Porting#30]
I'm sorry if my English is not correct because I'm using a translation.
Also, I am not very knowledgeable at all about Haxe, etc., so I am sorry if I have said something strange.

I wanted to port Psych Engine to Android, so I borrowed some code from this repository and tried to port it. However, when I tried to build it, it stopped with an error like the following picture:

![image](https://user-images.githubusercontent.com/90076182/209841070-1123aa62-d3c1-45ed-8603-187c45c11870.png)

I looked up this error on the internet and found information that adding
`<haxeflag name="--macro" value="allowPackage('flash')" />`
would solve it, but I don't even know where to add this.

Do I need to lower the version of something when building on Android?

Thank you.

**Comment by MAJigsaw77** [comment]
This isn't a issue that I'm responsible with, try to ask the engine devs or something

**Comment by Endergreen12** [comment]
> This isn't a issue that I'm responsible with, try to ask the engine devs or something

Ok, thanks

**Comment by Endergreen12** [comment]
I solved the problem and I'm leaving this as a reminder to myself and others who have encountered the same problem as I did...

I didn't need to lower the version of anything.
I solved this problem by installing lime's Development Builds:
https://github.com/openfl/lime/actions
