### ISSUE TITLE
Problem with screen size 

### ISSUE THREAD

**Issue by RonyxDumb** [MAJigsaw77/FNF-Android-Porting#34]
ehh the game looks like this 
![Screenshot_20230119_225320](https://user-images.githubusercontent.com/104029827/213570783-5900f9fd-76c6-4703-8b23-da71133486f5.png)

**Comment by MAJigsaw77** [comment]
This is not relevant to be posted here..

**Comment by RonyxDumb** [comment]
And where?

**Comment by RonyxDumb** [comment]
now I explain better, on PC I programmed it and it appears in its right screen, but for Android, it looks like this...
