### ISSUE TITLE
Error while compiling

### ISSUE THREAD

**Issue by cursedUs64-git** [MAJigsaw77/FNF-Android-Porting#35]
I use haxe 4.2.3 and this is the error

`source/Main.hx:75: characters 61-65 : Float should be Int
source/Main.hx:75: characters 61-65 : ... For optional function argument 'updateFramerate'
source/Main.hx:75: characters 61-65 : ... For function argument 'child'
source/editors/ChartingState.hx:382: characters 89-99 : Type not found : FileSystem
source/FreeplayState.hx:50: characters 71-74 : Float should be flixel.util.FlxAxes
source/FreeplayState.hx:50: characters 71-74 : ... For optional function argument 'repeatAxes'`

**Comment by cursedUs64-git** [comment]
ok i fixed it but now i get this error:

`source/editors/ChartingState.hx:382: characters 89-99 : Type not found : FileSystem
source/PlayState.hx:1864: characters 31-39 : Class<Paths> has no field modsJson
source/Paths.hx:230: characters 22-32 : Type not found : FileSystem
source/Paths.hx:233: characters 7-17 : Type not found : FileSystem
source/Paths.hx:241: characters 9-19 : Type not found : FileSystem
source/Paths.hx:246: characters 8-18 : Type not found : FileSystem`

**Comment by Stefan2008GitHub** [comment]
Report it on the Psych Engine server

**Comment by MAJigsaw77** [comment]
This error isn't relevant to be posted here...
