### ISSUE TITLE
Problems I encountered in porting Android ports

### ISSUE THREAD

**Issue by Liulw123** [MAJigsaw77/FNF-Android-Porting#36]
Can you tell me why it is getting smaller? I really can't find a solution
![image](https://github.com/Liulw123/test-1/blob/main/docs/img/Screenshot_20230128_181925.jpg)

**Comment by Liulw123** [comment]
sorry, i think i can delete some files

**Comment by Stefan2008GitHub** [comment]
You are just freaked something
