### ISSUE TITLE
SDL ERROR

### ISSUE THREAD

**Issue by RonyxDumb** [MAJigsaw77/FNF-Android-Porting#37]
![Screenshot_20230206_213330](https://user-images.githubusercontent.com/104029827/217079384-0bbd2eca-8ffb-4f10-9946-20d2cae52d32.png)

how do i fix it? I don't even know what caused it since libApplicatiobMain.so is there...

**Comment by MAJigsaw77** [comment]
This isn't a relevant issue for this repo...

**Comment by RonyxDumb** [comment]
Duh
