### ISSUE TITLE
smth broken

### ISSUE THREAD

**Issue by mcagabe19** [MAJigsaw77/FNF-Android-Porting#38]
if we add ``addMobileControls`` (deprecated but ``addHitbox`` same happens too) or ``addVirtualPadCamera`` in every added states hud is gone even at my mobile porting repo too but pad is here ig after updates cameras is fucked up and needs fix.

**Comment by MAJigsaw77** [comment]
You really didn't saw `DefaultDrawTarget` as a variable on cameras function -___-

**Comment by MAJigsaw77** [comment]
Just put it to false if the hud disappears

**Comment by mcagabe19** [comment]
well idk xd but yes i didnt see ``DefaultDrawTarget``

**Comment by mcagabe19** [comment]
@MAJigsaw77 but my recommend add a warning or smth to user add ``false`` into () idk
